# https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/
apiVersion: apps/v1 # version of Kubernetes API to use
kind: Deployment # type of object to create
metadata: # data to uniquely identify object
  name: testapp-deployment
  namespace: testapp
spec: # state of object
  replicas: 4 # number of pods to start
  selector: # this is how the deployment will find pods to manage
    matchLabels:
      app: testapp # if it matches the app name
  template: # template of the pod (ie, what is it)
    metadata: # metadata to uniquely identify the pod
      labels:
        app: testapp
    spec: # specification of the pod
      containers:
        - name: fastapitest # it will create a container named `fastapitest`
          image: jcfoxtrot54/fastapitest:latest # using this image from a container registry (Docker hub in this instance)
          ports: # which ports is the container listening on?
          - containerPort: 8000
---

kind: Service
apiVersion: v1
metadata:
  name: testapp-service
spec:
  selector:
    app: testapp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testapp-ingress
  namespace: testapp
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: k3stest.foxtrot-titan.co.uk
      http:
        paths:
          -
            path: /
            pathType: Prefix
            backend:
              service:
                name: testapp-service
                port:
                  number: 80
